# Generated by Django 4.0.1 on 2022-01-28 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=50, verbose_name='Emp_name')),
                ('joining_date', models.DateTimeField(verbose_name='Joining Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Record created on')),
            ],
        ),
    ]
