# Generated by Django 4.0.1 on 2022-01-31 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_add_employee_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dname', models.CharField(max_length=5, verbose_name='short name')),
                ('description', models.CharField(max_length=100, null=True, verbose_name='Full name')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=50, verbose_name='Project name')),
                ('budget', models.FloatField(null=True, verbose_name='Budget value')),
            ],
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Employee', 'verbose_name_plural': 'Employee'},
        ),
        migrations.AddField(
            model_name='employee',
            name='Department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.department'),
        ),
        migrations.AddField(
            model_name='employee',
            name='project',
            field=models.ManyToManyField(related_name='emp_project', to='app1.Project'),
        ),
    ]
